import Image from 'next/image';
import './globals.css';

import mainBackground from '../public/images/background.jpg';
import type { Metadata } from 'next';
import Header from '@/components/header';
import { NextAuthProvider } from './providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body suppressHydrationWarning>
        <NextAuthProvider>
          <div className='absolute -z-10 w-screen h-screen'>
            <Image
              src={mainBackground}
              alt='main background'
              quality={100}
              priority
              style={{
                height: '100%',
                width: '100%',
                objectFit: 'cover',
              }}
            />
          </div>
          <Header />
          <main>{children}</main>
        </NextAuthProvider>
      </body>
    </html>
  );
}
